/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SimonPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author Leo
 */
public class ScoreFrame extends javax.swing.JFrame {

    //private SimonGamePanel gamePanel;
    private SimonWelcome welcome;
    
    /**
     * Creates new form ScoreFrame
     *
     */
    public ScoreFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playAgainButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        simonHeaderLabel = new javax.swing.JLabel();
        score1label = new javax.swing.JLabel();
        score2Label = new javax.swing.JLabel();
        score3Label = new javax.swing.JLabel();
        score4Label = new javax.swing.JLabel();
        score5Label = new javax.swing.JLabel();
        score6Label = new javax.swing.JLabel();
        score7Label = new javax.swing.JLabel();
        score8Label = new javax.swing.JLabel();
        score9Label = new javax.swing.JLabel();
        score10Label = new javax.swing.JLabel();
        player1TextField = new javax.swing.JTextField();
        player2TextField = new javax.swing.JTextField();
        player3TextField = new javax.swing.JTextField();
        player4TextField = new javax.swing.JTextField();
        player5TextField = new javax.swing.JTextField();
        player6TextField = new javax.swing.JTextField();
        player7TextField = new javax.swing.JTextField();
        player8TextField = new javax.swing.JTextField();
        player9TextField = new javax.swing.JTextField();
        player10TextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        InstructionsMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        authorMenuItem = new javax.swing.JMenuItem();
        aboutSimonMenuItem = new javax.swing.JMenuItem();
        exitGameMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setName("WelcomeSimonFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));

        playAgainButton.setText("Play Again");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit Game");
        exitButton.setToolTipText("");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        simonHeaderLabel.setFont(new java.awt.Font("Gulim", 0, 36)); // NOI18N
        simonHeaderLabel.setText("S I M O N");

        score1label.setText("xxx");

        score2Label.setText("xxx");

        score3Label.setText("xxx");

        score4Label.setText("xxx");

        score5Label.setText("xxx");

        score6Label.setText("xxx");

        score7Label.setText("xxx");

        score8Label.setText("xxx");

        score9Label.setText("xxx");

        score10Label.setText("xxx");

        player1TextField.setEditable(false);
        player1TextField.setText("jTextField1");

        player2TextField.setEditable(false);
        player2TextField.setText("jTextField2");

        player3TextField.setEditable(false);
        player3TextField.setText("jTextField3");

        player4TextField.setEditable(false);
        player4TextField.setText("jTextField4");

        player5TextField.setEditable(false);
        player5TextField.setText("jTextField5");

        player6TextField.setEditable(false);
        player6TextField.setText("jTextField6");

        player7TextField.setEditable(false);
        player7TextField.setText("jTextField7");

        player8TextField.setEditable(false);
        player8TextField.setText("jTextField8");

        player9TextField.setEditable(false);
        player9TextField.setText("jTextField9");

        player10TextField.setEditable(false);
        player10TextField.setText("jTextField10");

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        helpMenu.setText("Help");

        InstructionsMenuItem.setText("Instructions");
        InstructionsMenuItem.setToolTipText("");
        InstructionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(InstructionsMenuItem);

        jMenuBar1.add(helpMenu);

        aboutMenu.setText("About");

        authorMenuItem.setText("Author Info");
        authorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(authorMenuItem);

        aboutSimonMenuItem.setText("About Simon");
        aboutSimonMenuItem.setToolTipText("");
        aboutSimonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutSimonMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutSimonMenuItem);

        jMenuBar1.add(aboutMenu);

        exitGameMenu.setText("Exit Game");

        ExitMenuItem.setText("Exit");
        ExitMenuItem.setToolTipText("");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        exitGameMenu.add(ExitMenuItem);

        jMenuBar1.add(exitGameMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(playAgainButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simonHeaderLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player9TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score9Label)
                            .addComponent(score10Label)
                            .addComponent(score8Label)
                            .addComponent(score7Label)
                            .addComponent(score6Label)
                            .addComponent(score5Label)
                            .addComponent(score4Label)
                            .addComponent(score3Label)
                            .addComponent(score2Label)
                            .addComponent(score1label))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(simonHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(score1label)
                    .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(score2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score3Label)
                    .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score4Label)
                    .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score5Label)
                    .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score6Label)
                    .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score7Label)
                    .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score8Label)
                    .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score9Label)
                    .addComponent(player9TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score10Label)
                    .addComponent(player10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("You have pressed the play again button");
        //gamePanel = new SimonGamePanel();
        //gamePanel.setUI(null);
        //gamePanel.setVisible(true);
        welcome = new SimonWelcome();
        welcome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void InstructionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("You have selected the Instructions menu item");
        JOptionPane.showMessageDialog(this,"Rules:   The rules are very simple.  Enter the same\n"
					+ "pattern as displayed by the game.  There is no time\n"
					+ "limit.  As long as you can enter the same pattern\n"
                                        + "each time, the game continues.  Each time you\n"
                                        + "successfully enter the complete pattern, you get\n"
                                        + "a point.",
					"Instructions",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InstructionsMenuItemActionPerformed

    private void authorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("You have pressed the author info menu item");
        JOptionPane.showMessageDialog(this,"          S I M O N         \n"
		+  "                                \n"
		+  "          Developed by          \n"
		+  "                                \n"
		+  "         Leo Gutierrez          \n"
                +  "          For CSC18B            \n"
                +  "     Java Advanced Objects      \n",
		"THE AUTHORS",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_authorMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void aboutSimonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutSimonMenuItemActionPerformed
        // TODO add your handling code here:
        System.out.println("You have pressed the ");
        JOptionPane.showMessageDialog(this,"This is a replica of the original Simon\n"
					+ "memory game that was released in 1978.\n",
					"Instructions",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutSimonMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem InstructionsMenuItem;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem aboutSimonMenuItem;
    private javax.swing.JMenuItem authorMenuItem;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenu exitGameMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JTextField player10TextField;
    private javax.swing.JTextField player1TextField;
    private javax.swing.JTextField player2TextField;
    private javax.swing.JTextField player3TextField;
    private javax.swing.JTextField player4TextField;
    private javax.swing.JTextField player5TextField;
    private javax.swing.JTextField player6TextField;
    private javax.swing.JTextField player7TextField;
    private javax.swing.JTextField player8TextField;
    private javax.swing.JTextField player9TextField;
    private javax.swing.JLabel score10Label;
    private javax.swing.JLabel score1label;
    private javax.swing.JLabel score2Label;
    private javax.swing.JLabel score3Label;
    private javax.swing.JLabel score4Label;
    private javax.swing.JLabel score5Label;
    private javax.swing.JLabel score6Label;
    private javax.swing.JLabel score7Label;
    private javax.swing.JLabel score8Label;
    private javax.swing.JLabel score9Label;
    private javax.swing.JLabel simonHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
