package com.GutierrezLeo.CSC18B.SimonGame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Leo Gutierrez
 * 			CIC18B	-	Java Advanced Object
 * 			Dr Mark Lehr
 * 			Riverside City College
 */
public class SimonWelcome extends javax.swing.JFrame {

    /**
     * Creates new form SimonWelcome
     */
    
	// Declare the game panel class
	private RegisterPanel registerPanel;
    private SimonGamePanel gamePanel;
    //private RegisterFrame r = new RegisterFrame();
    
    // Constructor to the splash screen
    public SimonWelcome() {
    	
        initComponents();
        getContentPane().setBackground(Color.BLACK); 
        System.out.println("You are in the SimonWelcome constructor");
        colorfulSimon();
        placeArcPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	// Declare all the buttons and labels to the splash screen
        playButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        simonDescriptionScollPane = new javax.swing.JScrollPane();
        simonDescriptionTextArea = new javax.swing.JTextArea();
        sLabel = new javax.swing.JLabel();
        iLabel = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        oLabel = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();

        // Set the splash screen parametsw
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcom to S I M O N");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setName("SimonWelcome"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        // Play button details
        playButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        playButton.setText("Play");
        //playButton.setOpaque(true);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        
        // Exit button details
        exitButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        // Scroll pane details
        //simonDescriptionScollPane.setBackground(new java.awt.Color(0, 0, 0));
        simonDescriptionScollPane.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        simonDescriptionTextArea.setEditable(false);
        simonDescriptionTextArea.setBackground(Color.BLACK);
        simonDescriptionTextArea.setForeground(Color.YELLOW);
        simonDescriptionTextArea.setColumns(20);
        simonDescriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        simonDescriptionTextArea.setLineWrap(true);
        simonDescriptionTextArea.setRows(5);
        
        Border empty;
        empty = BorderFactory.createEmptyBorder();
        simonDescriptionScollPane.setBorder(empty);
        
        simonDescriptionTextArea.setText("    Do what SIMON says...\n\n Follow the pattern of lights\n   "
        		+ "and sounds for as long as\n"
        		+ "                  you can...");
        simonDescriptionTextArea.setWrapStyleWord(true);
        simonDescriptionTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        simonDescriptionScollPane.setViewportView(simonDescriptionTextArea);

        
        // Individual SIMON labels for each letter.  Coded this way to change the color for each letter constantly while the splash
        // screen is visible.
        
        // S Label
        sLabel.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        sLabel.setBackground(Color.BLACK);
        //sLabel.setForeground(Color.WHITE);
        sLabel.setText("S");
        
        // I Label
        iLabel.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        //iLabel.setForeground(new java.awt.Color(255, 255, 255));
        //iLabel.setForeground(Color.WHITE);
        iLabel.setBackground(Color.BLACK);
        iLabel.setText("I");

        // M Label
        mLabel.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        //mLabel.setForeground(new java.awt.Color(255, 255, 255));
        mLabel.setBackground(Color.BLACK);
        //mLabel.setForeground(Color.WHITE);
        mLabel.setText("M");

        // O Label
        oLabel.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        //oLabel.setForeground(new java.awt.Color(255, 255, 255));
        oLabel.setBackground(Color.BLACK);
        //oLabel.setForeground(Color.WHITE);
        oLabel.setText("O");

        // N Label
        nLabel.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        //nLabel.setForeground(new java.awt.Color(255, 255, 255));
        nLabel.setBackground(Color.BLACK);
        //nLabel.setForeground(Color.WHITE);
        nLabel.setText("N");
        
        
        // Horizontal and Vertical group layouts for the items on the spash screen
        //    Automated in NetBeans using the GUI Builder
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(sLabel)
                        .addGap(18, 18, 18)
                        .addComponent(iLabel)
                        .addGap(18, 18, 18)
                        .addComponent(mLabel)
                        .addGap(18, 18, 18)
                        .addComponent(oLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(playButton)
                            .addComponent(exitButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(simonDescriptionScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel)
                    .addComponent(iLabel)
                    .addComponent(mLabel)
                    .addComponent(oLabel)
                    .addComponent(nLabel))
                .addGap(37, 37, 37)
                .addComponent(simonDescriptionScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(playButton)
                .addGap(75, 75, 75)
                .addComponent(exitButton)
                .addGap(115, 115, 115))
        );

        pack();
        
    }// </editor-fold>                        

    // Call and place the Arc Panel 
    private void placeArcPanel(){
    	
    	arcsJPanel = new ArcsJPanel();
        getContentPane().add(arcsJPanel);
        //add(gamePanel);
        arcsJPanel.setBackground(Color.BLACK);
        arcsJPanel.setSize(260, 170);
        arcsJPanel.setLocation(80, 227);
        //pack();
        arcsJPanel.setVisible(true);
    	
    }
    
    // The colorful SIMON labels
    private void colorfulSimon(){
    	
    	sLabel.setForeground(Color.BLUE);
		iLabel.setForeground(Color.RED);
		mLabel.setForeground(Color.GREEN);
		oLabel.setForeground(Color.YELLOW);
		nLabel.setForeground(Color.MAGENTA);
    	
    	/*
    	do{
        	System.out.println("You are in the while loop");
        	for (int x = 0; x > 500000; x++){
        		System.out.println("You are in the for loop");
        		System.out.println(x);
        		if (x < 100000){
        			sLabel.setForeground(Color.BLUE);
        			iLabel.setForeground(Color.RED);
        			mLabel.setForeground(Color.GREEN);
        			oLabel.setForeground(Color.YELLOW);
        			nLabel.setForeground(Color.MAGENTA);
        		} else if(x >= 100000 && x < 200000){
        				sLabel.setForeground(Color.GREEN);
            			iLabel.setForeground(Color.YELLOW);
            			mLabel.setForeground(Color.MAGENTA);
            			oLabel.setForeground(Color.RED);
            			nLabel.setForeground(Color.BLUE);
        			} else if (x >= 200000 && x < 300000){
        				sLabel.setForeground(Color.RED);
            			iLabel.setForeground(Color.GREEN);
            			mLabel.setForeground(Color.BLUE);
            			oLabel.setForeground(Color.MAGENTA);
            			nLabel.setForeground(Color.YELLOW);
        			} else if (x >= 300000 && x < 400000){
        				sLabel.setForeground(Color.YELLOW);
            			iLabel.setForeground(Color.MAGENTA);
            			mLabel.setForeground(Color.RED);
            			oLabel.setForeground(Color.BLUE);
            			nLabel.setForeground(Color.GREEN);
        			}
        		}
    			
        	
        } while (this.isVisible());
    	*/
    }
    
    // Play Button action defined
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("You have pressed the play button in SimonWelcome");
        remove(playButton);
        remove(exitButton);
        remove(simonDescriptionTextArea);
        remove(simonDescriptionScollPane);
        remove(sLabel);
        remove(iLabel);
        remove(mLabel);
        remove(oLabel);
        remove(nLabel);
        remove(arcsJPanel);
        gamePanel = new SimonGamePanel();
        getContentPane().add(gamePanel);
        //add(gamePanel);
        gamePanel.setBackground(Color.BLACK);
        gamePanel.setSize(600, 600);
        pack();
        gamePanel.setVisible(true);
    }                                          

    
    // Exit button action defined
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0); 
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimonWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimonWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimonWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimonWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimonWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel sLabel;
    private javax.swing.JLabel iLabel;
    private javax.swing.JLabel mLabel;
    private javax.swing.JLabel nLabel;
    private javax.swing.JLabel oLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JScrollPane simonDescriptionScollPane;
    private javax.swing.JTextArea simonDescriptionTextArea;
    private ArcsJPanel arcsJPanel;
    private RegisterFrame r = new RegisterFrame();

    // End of variables declaration                   
}
